#!/usr/bin/env python3
"""Smoke test for Step 4 - Answer Generator (via pipeline_runner).

Run from the ai_server directory:
    python tests/smoke_step4.py

Requirements:
  - ollama serve running + gemma3:1b pulled
  - Qdrant running with MPG SOP document indexed
  - FastAPI server running on localhost:8000 (for the HTTP test at the end)

No pytest, no fixtures. Plain Python script.
"""
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ai.agents.models.session import SessionContext
from ai.pipeline.pipeline_runner import run_pipeline

QUERIES = [
    "What are the steps to process a freight shortage claim and what documentation is required?",
    "What does RPOD mean and how is it different from a standard POD?",
    "Who is responsible for managing theft incidents at MPG USA and what is their contact?",
    "Who won the FIFA World Cup in 2022?",
    "Can you write a poem about ocean waves?",
    "How do I escalate a carrier dispute?",
    "What happens after an RA is approved?",
    "What about the timeline?",
    "Can you explain more about that?",
    "Can you put that in bullet points?",
]

SEP = "-" * 80


def main() -> None:
    generated_count = 0
    refused_count = 0
    confidence_failed_count = 0
    total_gen_latency = 0.0

    total = len(QUERIES)
    print(SEP)
    print(f"Smoke Test: Step 4 - Answer Generator  ({total} queries)")
    print(SEP)

    wall_start = time.perf_counter()

    for i, query in enumerate(QUERIES, start=1):
        state = run_pipeline(query, SessionContext(session_id=f"smoke4-{i}"))
        rr = state.retrieval_result
        cr = state.confidence_result
        ar = state.answer_result

        was_refused = rr.was_refused if rr else False
        confidence_passed = cr.passed if cr else False

        print(f"\nQuery {i}/{total}: {query}")
        print(f"  was_refused        : {was_refused}")
        print(f"  confidence_passed  : {confidence_passed}")
        print(f"  was_generated      : {ar.was_generated}")
        print(f"  model_used         : {ar.model_used}")
        print(f"  no_think_injected  : {ar.no_think_injected}")
        print(f"  latency_ms         : {ar.latency_ms:.0f}ms")
        print(f"  prompt_tokens~     : {ar.prompt_token_estimate}")
        print(f"  skip_reason        : {ar.skip_reason}")
        print("  --- ANSWER ---")
        print(ar.answer_text)
        print(SEP)

        if ar.was_generated:
            generated_count += 1
            total_gen_latency += ar.latency_ms
        elif was_refused:
            refused_count += 1
        elif not confidence_passed:
            confidence_failed_count += 1

    wall_elapsed = (time.perf_counter() - wall_start) * 1000
    avg_latency = total_gen_latency / generated_count if generated_count > 0 else 0.0

    print(f"\n{'=' * 80}")
    print("SUMMARY")
    print(f"{'=' * 80}")
    print(f"  {generated_count}/10 answers generated by LLM")
    print(f"  {refused_count}/10 refused by Group 1 (no LLM call)")
    print(f"  {confidence_failed_count}/10 failed confidence gate (no LLM call)")
    print(f"  Total wall time       : {wall_elapsed:.0f}ms")
    print(f"  Avg latency (gen only): {avg_latency:.0f}ms")

    # ------------------------------------------------------------------
    # HTTP endpoint test
    # ------------------------------------------------------------------
    print(f"\n{'=' * 80}")
    print("HTTP Endpoint Test: POST /api/qa/ask")
    print(f"{'=' * 80}")
    try:
        import httpx

        test_query = (
            "What is the step-by-step process for filing a freight "
            "shortage claim and what documentation is required?"
        )
        resp = httpx.post(
            "http://localhost:8000/api/qa/ask",
            json={"query": test_query},
            timeout=180.0,
        )
        print(f"  status_code    : {resp.status_code}")
        import json
        data = resp.json()
        print(f"  response JSON  :")
        print(json.dumps(data, indent=2))
    except Exception as exc:
        print(f"  HTTP test failed (is the FastAPI server running?): {exc}")


if __name__ == "__main__":
    main()
